### PR TITLE
#42:New releaseBuild argument and some documentation improvement

### PR DESCRIPTION
**Pull request by vlk32**
This code is straightforward, so I was able implement this improvement.
Please check it.

### CODE REVIEW

**Comment by dcoraboeuf** [comment]
Thanks for the PR. It looks really OK to me.

Would it be possible to add one or two tests?

**Comment by dcoraboeuf** [comment]
Any by the way, thanks you for the documentation update. Very much appreciated :)

**Comment by dcoraboeuf** [comment]
Thanks Vladimir,

I'll try to check the code next week (too busy right now...)

Best regards,
Damien

**Comment by vlk32** [comment]
> I'll try to check the code next week

It's OK. I'm also short of time, so I did this fix in late evening, maybe it's "night code" :-(

Maybe it could be usefull to know how that tests were implemented :
1.) `cp GitVersionTest.groovy GitVersionReleaseBuildTrueTest.groovy`
2.) I manually added `releaseBuild = true`
3.) ... it was without any failures
4.) `cp GitVersionReleaseBuildTrueTest.groovy GitVersionReleaseBuildFalseTest.groovy`
5.) I replace `releaseBuild = true` to `releaseBuild = false`
6.) ... there was 3 failures, but I create separate commit 
7.) I fixed that failures and created second commit.

**Comment by dcoraboeuf** [comment]
Tests are indeed passing now. I'm merging.

**Pull request merged**
