### PR TITLE
upgraded to the latest GrGit and JGit

### PR DESCRIPTION
**Pull request by musketyr**
sadly, the API for JGit is envolving without much backward compatibility. this plugin currently breaks the build if some other plugin with a newer version of JGit is applied.

### CODE REVIEW

**Comment by aalmiray** [comment]
Hi @dcoraboeuf, any news on this update? :smile:

**Comment by dcoraboeuf** [comment]
Hi, because of a concurrent PR, I now have a conflict on this one. Is that possible to get it fixed?

**Comment by aalmiray** [comment]
I suppose this is PR #59. I’d suggest to first merge that PR if the changes are acceptable, then @musketyr may be able to rebase this PR and resubmit.

**Comment by dcoraboeuf** [comment]
The conflict is due to the PR #72 having been merged, and there is some code conflict now.

I'll wait a bit to check if @musketyr can rebased on the `master` branch. If not, I'll create another branch to upgrade the code.

**Comment by musketyr** [comment]
I'm on vacation right now but I will take a look once I'm back.

**Comment by musketyr** [comment]
@dcoraboeuf updated

**Pull request merged**
